### ISSUE TITLE
i scanned my c driver with the tool

### ISSUE THREAD

**Issue by Marthmoon** [p32929/Shortcut-Virus-Remover#1]
first i scanned the usb driver with the tool, then i scanned my C driver too, now all the shortcuts in the taskbar and desktop are gone, even the file explorer, the shortcut virus still remained though, also there is a Note file called desktop.ini which is in every folder, and it opens up in a note when i startup the device. help please,

**Comment by p32929** [comment]
Oh dear, when I initially created this script, I hadn't considered using it on the C (system) drive. It's important to note that the script only removes the shortcuts created on a drive and does not necessarily remove the program that generates those shortcuts.

Here's what you can do:

You will need to reinstall your operating system. It's advisable to back up any important files from your C drive and then format the C drive during the reinstallation of Windows.

This process should completely remove the virus and restore the original Windows shortcuts.

**Comment by p32929** [comment]
when I initially created this script, I hadn't considered using it on the C (system) drive. It's important to note that the script only removes the shortcuts created on a drive and does not necessarily remove the program that generates those shortcuts.

Here's what you can do:

You will need to reinstall your operating system. It's advisable to back up any important files from your C drive and then format the C drive during the reinstallation of Windows.

This process should completely remove the virus and restore the original Windows shortcuts.
